# Site settings
title: New awesome title
author: Smart guy
name: Evan Will
email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima

theme: jekyll-theme-minimal